"""add task created_by

Revision ID: 4663c6112208
Revises: c2c1b9e11715
Create Date: 2026-06-21 15:30:44.139495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4663c6112208'
down_revision: Union[str, Sequence[str], None] = 'c2c1b9e11715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_by_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_tasks_created_by_id'), 'tasks', ['created_by_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_created_by_id'), table_name='tasks')
    op.drop_column('tasks', 'created_by_id')
    # ### end Alembic commands ###
