"""add task indexes

Revision ID: c2c1b9e11715
Revises: 79982f20ea63
Create Date: 2026-06-21 15:19:41.220311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c1b9e11715'
down_revision: Union[str, Sequence[str], None] = '79982f20ea63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tasks_project_assignee', 'tasks', ['project_id', 'assignee_id'], unique=False)
    op.create_index('ix_tasks_project_created', 'tasks', ['project_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_tasks_project_priority', 'tasks', ['project_id', 'priority'], unique=False)
    op.create_index('ix_tasks_project_status', 'tasks', ['project_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_project_status', table_name='tasks')
    op.drop_index('ix_tasks_project_priority', table_name='tasks')
    op.drop_index('ix_tasks_project_created', table_name='tasks')
    op.drop_index('ix_tasks_project_assignee', table_name='tasks')
    # ### end Alembic commands ###
